---
title: "example1"
author: "Jessica McMaster"
output: html_document
date: "2022-12-01"
---
```{r load-data, message=FALSE}
library(tidyverse) # used for data manipulation
library(rmarkdown) # used for paged_table function
library(kableExtra) # used for table
library(ggpubr) #used for ggarrange function 

#load dataset 
pop_data <- read_csv("data/gapminder_data.csv")

#create a table with data from European countries in 2007 showing the countries 
#with the largest life expectancy at the top 
euro_data_tbl <- pop_data %>% 
                    filter(continent == "Europe" & year == 2007) %>% 
                    select(-continent, -year) %>% 
                    arrange(desc(lifeExp)) %>% 
                    rename(Country = country, "Population Size" = pop, 
                      "Life Expectancy" = lifeExp, "GDP" = gdpPercap)
```

The results in euro_data_tbl are displayed in the Table below:

```{r kbl}
euro_data_tbl %>% 
          kable(caption="European countries ordered by greatest life expectancy from 2007 data") %>% 
          kable_styling(bootstrap_options = "striped", full_width = F) %>% 
          column_spec(2, width = "30em", background = "pink") %>% 
          scroll_box(width = "100%", height = "200px")
```
```{r paged-table}
paged_table(euro_data_tbl)
```
```{r adding-images}
#keep only United Kingdom data and change year to factor
uk_data_fig <- pop_data %>%
                    filter(country == "United Kingdom") %>%
                    mutate(year=as_factor(year))

```
```{r}

euro_data_fig <- pop_data %>% 
                    filter(continent == "Europe")  %>% 
                    mutate(year=as_factor(year))

```
The life expectancy for Europe over the years is plotted as following:

```{r fig, warning=FALSE, fig.cap="Life Expectancy in Europe over the years"}
#Euro plot
euro_plot <- euro_data_fig %>%
                ggplot(mapping=aes(x=year, y=lifeExp)) +
                geom_violin() +
                stat_summary(fun.y = median, geom = "point")



#draw euro plot
euro_plot

```
```{r fig-comp, warning=FALSE, fig.cap="Life Expectancy in European and UK over the years"}
#UK plot
uk_plot <- uk_data_fig %>%
                ggplot(mapping=aes(x=year, y=lifeExp)) +
                geom_point()

#draw euro plot next to UK plot
ggarrange(euro_plot, uk_plot, ncol=2, nrow=1, labels="AUTO")
```